name = "sun-panel"
main = "src/index.ts"
compatibility_date = "2025-05-01"

[assets]
directory = "./frontend/dist"

[observability]
enabled = true
head_sampling_rate = 0.1

[[d1_databases]]
binding = "DB"
database_name = "sun-panel-db"
database_id = "__D1_DATABASE_ID__"